### Flashcards

<details>
<summary>What 2 problems in n-gram / tf-idf does word embeddings solve?</summary>

1. Similar words don't have similar representation (help vs assitance)
    > Similar words have similar vectors
2. Vector size is too large (vector is sparse and size of the entire corpus)
   > Vector size can be manually set (dimensions are low)
</details>


![](https://i.imgur.com/8ucXB3v.png)

![](https://i.imgur.com/MTzWBX0.png)

- Model Variations

![](https://i.imgur.com/Kqvk8hF.png) 

![](https://i.imgur.com/qoSwkWc.png)



![](https://i.imgur.com/3pVJO0W.png) 

### Code Implementation

In [3]:
import spacy

https://spacy.io/models/en

This requires the large (lg) or medium (md) model as the small (sm) model does not have vectors

- en_core_web_lg -- 685k keys, 343k unique vectors (300 dimensions)
- en_core_web_md -- 685k keys, 20k unique vectors (300 dimensions)


In [ ]:
!python -m spacy download en_core_web_lg

In [5]:
nlp = spacy.load("en_core_web_lg")

In [11]:
doc = nlp("In the southern sky, adfdfkdgsj Franz Yash")

for token in doc:
    print(token.text, token.has_vector, not token.is_oov)

In True True
the True True
southern True True
sky True True
, True True
adfdfkdgsj False False
Franz True True
Yash True True


In [15]:
doc[0].vector.shape

(300,)

In [16]:
doc = nlp('''
In the southern sky, I see a light that is shining into the night.
Looking at it I remember what I'm meant to recall.
That what I hear right now in front of me was once such a song.
''')

In [19]:
doc.vector.shape

(300,)

In [20]:
base_token = nlp("bread")

In [53]:
tokens = nlp('bread sandwich butter rice pita person wheat computer cat mage')

for token in tokens:
    # This calculates cosine similarity
    print(token.text, token.similarity(base_token))

bread 0.9999999744752309
sandwich 0.6341067417450952
butter 0.7212939096748688
rice 0.6082261546210023
pita 0.5335656224460084
person 0.2385450112052788
wheat 0.615036141030184
computer 0.14402428531962433
cat 0.1255933926864667
mage 0.015320008784434172


- two words in similar context will have more similarity
- breat and butter, profit and loss

In [30]:
def print_similarity(base_word, words):

    base_token = nlp(base_word)
    tokens = nlp(words)

    for token in tokens:
        print(f"{token.text:<8} {round(token.similarity(base_token),3)}")

In [35]:
print_similarity('profit', 'gain loss money bread value cat water')

gain     0.352
loss     0.24
money    0.516
bread    0.171
value    0.523
cat      -0.065
water    0.16


In [38]:
print_similarity('iphone', 'apple samsung phone ipad android cat steve stevejobe')

apple    0.439
samsung  0.671
phone    0.729
ipad     0.774
android  0.674
cat      0.114
steve    0.122
stevejobe 0.0


<ipython-input-30-28b6d42a0d6d>:7: UserWarning: [W008] Evaluating Token.similarity based on empty vectors.
  print(f"{token.text:<8} {round(token.similarity(base_token),3)}")


In [42]:
vv = lambda word: nlp.vocab[word].vector

In [46]:
result = vv('king') - vv('man') + vv('woman')

In [50]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity([result], [vv('queen')])

array([[0.6178014]], dtype=float32)

In [51]:
cosine_similarity([result], [vv('king')])

array([[0.8489542]], dtype=float32)

In [52]:
cosine_similarity([vv('king')], [vv('queen')])

array([[0.61088413]], dtype=float32)

- result is supposed to be more similar to queen because of the vector arithmetic
- explore this later

### Text Classificcation using Spacy Word Vectors

Problem Statement

Using classical NLP techniques classify whether a given message/ text is **Real or Fake** Message.

We will use **glove embeddings** from spacy which is trained on massive wikipedia dataset to pre-process and text vectorization and apply different classification algorithms.

Dataset

Credits: https://www.kaggle.com/datasets/clmentbisaillon/fake-and-real-news-dataset

This data consists of two columns. - Text - label

Text is the statements or messages regarding a particular event/situation.

label feature tells whether the given text is Fake or Real.

As there are only 2 classes, this problem comes under the **Binary Classification**.

In [56]:
!wget -O Fake_Real_Data.csv https://raw.githubusercontent.com/codebasics/nlp-tutorials/main/14_word_vectors_spacy_text_classification/Fake_Real_Data.csv

--2025-01-16 10:30:28--  https://raw.githubusercontent.com/codebasics/nlp-tutorials/main/14_word_vectors_spacy_text_classification/Fake_Real_Data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25876225 (25M) [text/plain]
Saving to: ‘Fake_Real_Data.csv’

Fake_Real_Data.csv  100%[===================>]  24.68M  41.8MB/s    in 0.6s    

2025-01-16 10:30:39 (41.8 MB/s) - ‘Fake_Real_Data.csv’ saved [25876225/25876225]



In [58]:
import pandas as pd

df = pd.read_csv('/kaggle/working/Fake_Real_Data.csv')

In [59]:
df

Text label
0      Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake
1     U.S. conservative leader optimistic of common ...  Real
2     Trump proposes U.S. tax overhaul, stirs concer...  Real
3      Court Forces Ohio To Allow Millions Of Illega...  Fake
4     Democrats say Trump agrees to work on immigrat...  Real
...                                                 ...   ...
9895   Wikileaks Admits To Screwing Up IMMENSELY Wit...  Fake
9896  Trump consults Republican senators on Fed chie...  Real
9897  Trump lawyers say judge lacks jurisdiction for...  Real
9898   WATCH: Right-Wing Pastor Falsely Credits Trum...  Fake
9899   Sean Spicer HILARIOUSLY Branded As Chickensh*...  Fake

[9900 rows x 2 columns]

In [60]:
df['label'].value_counts()

label
Fake    5000
Real    4900
Name: count, dtype: int64

In [61]:
df['fake'] = df['label'].apply(lambda x: 1 if x == 'Fake' else 0)
# df['fake'] = df['label'].map({'Fake' : 1, 'Real' : 0})

In [63]:
df.iloc[0]

Text      Top Trump Surrogate BRUTALLY Stabs Him In The...
label                                                 Fake
fake                                                     1
Name: 0, dtype: object

In [64]:
import spacy
nlp = spacy.load('en_core_web_lg')

In [66]:
df['vector'] = df['Text'].apply(lambda x: nlp(x).vector)

In [67]:
df

Text label  fake  \
0      Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake     1   
1     U.S. conservative leader optimistic of common ...  Real     0   
2     Trump proposes U.S. tax overhaul, stirs concer...  Real     0   
3      Court Forces Ohio To Allow Millions Of Illega...  Fake     1   
4     Democrats say Trump agrees to work on immigrat...  Real     0   
...                                                 ...   ...   ...   
9895   Wikileaks Admits To Screwing Up IMMENSELY Wit...  Fake     1   
9896  Trump consults Republican senators on Fed chie...  Real     0   
9897  Trump lawyers say judge lacks jurisdiction for...  Real     0   
9898   WATCH: Right-Wing Pastor Falsely Credits Trum...  Fake     1   
9899   Sean Spicer HILARIOUSLY Branded As Chickensh*...  Fake     1   

                                                 vector  
0     [-0.6759837, 1.4263071, -2.318466, -0.451093, ...  
1     [-1.8355803, 1.3101058, -2.4919677, 1.0268308,...  
2     [-1.9851209, 0.14389805, -2.4221718, 0.9133005...  
3     [-2.7812982, -0.16120885, -1.609772, 1.3624227...  
4     [-2.2010763, 0.9961637, -2.4088492, 1.128273, ...  
...                                                 ...  
9895  [-1.6682401, 0.78006977, -2.2337353, -0.159771...  
9896  [-1.9297235, 0.8007302, -1.8990824, 0.42668718...  
9897  [-1.5289013, 1.0250993, -1.9861357, 0.4278564,...  
9898  [-1.3928099, 0.7792715, -2.2072845, 0.13192406...  
9899  [-1.5856593, -0.31769615, -0.9302766, 0.330447...  

[9900 rows x 4 columns]

In [69]:
df.to_csv('Fake_Real_Data_Processed.csv', index=False)

In [73]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df['vector'].values,
    df['fake'],
    test_size = 0.2,
    random_state = 1,
    stratify = df['fake']
)

In [75]:
X_train.shape

(7920,)

In [81]:
# This X_train is np arrays (object) nested in a np array
# We need to convert this to 2d np array

import numpy as np

X_train = np.stack(X_train)
X_test = np.stack(X_test)

In [82]:
X_train.shape

(7920, 300)